### ISSUE TITLE
Media Status

### ISSUE THREAD

**Issue by SmartManoj** [JayXT/MessengerComparison#13]
Media Status
Telegram has channel and Telescope

**Comment by JayXT** [comment]
Personally I would like to treat these features as a replacement too, but Media Status has deeper integration with WhatsApp than Telescope website with Telegram, it sends 24-hour duration custom status updates to all contacts. Channels at the same time require people to be subscribed to channel. In my opinion Media Status is useless for messengers, but some people might consider it as useful feature, which doesn't have a direct alternative in case of Telegram. Anyway thank you for suggestion, I might think of changing this part from disadvantage to mediocrity in the future.

**Comment by SmartManoj** [comment]
With bots we can set timer for messages, we could add users to our channel via Telethon,
For new contacts , we can add the link to bio

**Comment by JayXT** [comment]
These measures could work, with only exceptiothey want to subscribe to channel or not. This will likely result in complaints and reports on channel that will lead to its blocking sooner or later.

**Comment by SmartManoj** [comment]
> we could add users to our channel via Telethon,

Perhaps we could add our contacts to our channel via Telethon if need, or just share the url at once

**Comment by JayXT** [comment]
These doesn't resolve the main issues of channel blocking by user reporting, clearing it's subscribers by anti-cheat mechanisms or overcoming existing limit for manual adding of only up to 200 contacts to your channel.

**Comment by SmartManoj** [comment]
If we block someone from our channel, will they able to access telescope?

**Comment by JayXT** [comment]
As far as I know telesco.pe is completely public service available for everyone. Blocking subscribers shouldn't limit access to this website.

**Comment by JayXT** [comment]
Hey SmartManoj,
I thought through your suggestion and concluded that it really makes sense to reconsider Telegram Media Status support as mediocrity. Changes were added.
