### ISSUE TITLE
Жесткая Привязка к Мобильным Клиентам

### ISSUE THREAD

**Issue by nibytes** [JayXT/MessengerComparison#2]
Telegram: Для секретных чатов присутствует.

**Comment by JayXT** [comment]
Здесь имеется ввиду необходимость установки мобильного приложения для того, чтобы пользоваться им на десктопе. В Telegram такой необходимости нет и им можно пользоваться даже не имея смартфона, а лишь компьютер. Отсутствие поддержки секретных чатов на компьютере это уже другая вещь, которая является следствием кросс-платформенных ограничений безопасности.
