### ISSUE TITLE
Telegram: Contacting users

### ISSUE THREAD

**Issue by mrbesen** [JayXT/MessengerComparison#6]
With the new Version (5.8) you can actually contact persons without sharing username nor phone number by just using the "find near by people" feature

https://telegram.org/blog/contacts-local-groups

**Comment by JayXT** [comment]
Yes, this is additional way to contact people that is mentioned in other section of table (Communication Methods). For now I'll leave it as is, because to find other person based on location both of you have to open separate menu.
