### ISSUE TITLE
Suggestion: anchor link for any category-container

### ISSUE THREAD

**Issue by DMJWorld** [JayXT/MessengerComparison#66]

**Comment by JayXT** [comment]
Do you mean something of the following kind?
![image](https://user-images.githubusercontent.com/8045344/123599967-ddee9e80-d7fe-11eb-911c-047cd5b5b431.png)

**Comment by JayXT** [comment]
Anyway, a similar idea came to my mind few days ago. If implementation doesn't require any JS (I suppose not), I'll ponder on the best way to add it.

**Comment by JayXT** [comment]
Simple implementation of category anchors has been provisioned. Closing this issue.
